// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class AddQuestion_ChoicesResult
    {
        [Column("Question_Id", TypeName = "decimal(38,0)")]
        public decimal? Question_Id { get; set; }
    }
}
