// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class BranchTrack
{
    public int BranchId { get; set; }

    public int TrackId { get; set; }

    public int BrTrId { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual Track Track { get; set; }
}