// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Branch
{
    public int BranchId { get; set; }

    public string BranchName { get; set; }

    public virtual ICollection<BranchTrack> BranchTracks { get; set; } = new List<BranchTrack>();

    public virtual ICollection<Instructor> Instructors { get; set; } = new List<Instructor>();
}