// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Branch
{
    public int BranchId { get; set; }

    public string BranchName { get; set; }

    public virtual ICollection<Track> Tracks { get; set; } = new List<Track>();
}