// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Choice
{
    public int Choice_ID { get; set; }

    public string Choice_Text { get; set; }

    public int? Question_ID { get; set; }

    public virtual Question Question { get; set; }
}