// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Exam
{
    public int Exam_ID { get; set; }

    public DateOnly? Exam_Date { get; set; }

    public int? Exam_Duration { get; set; }

    public int? Course_ID { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Student_Exam_Question> Student_Exam_Questions { get; set; } = new List<Student_Exam_Question>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}