// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class GetAllChoicesResult
    {
        public int Choice_ID { get; set; }
        public string Choice_Text { get; set; }
        public int? Question_ID { get; set; }
    }
}
