// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class GetExamsResult
    {
        public int Exam_ID { get; set; }
        public DateOnly? Exam_Date { get; set; }
        public int? Exam_Duration { get; set; }
        public int? Course_ID { get; set; }
        public int? BrTr_ID { get; set; }
    }
}
