// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class GetInstructor_Courses_StudentsResult
    {
        public int Course_ID { get; set; }
        public string Course_Name { get; set; }
        public int? Number_Of_Students { get; set; }
    }
}
