// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class GetInstructorsResult
    {
        public int Instructor_ID { get; set; }
        public string Instructor_Name { get; set; }
    }
}
