// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Instructor
{
    public int Instructor_ID { get; set; }

    public string Instructor_Fname { get; set; }

    public string Instructor_Lname { get; set; }

    public string Instructor_Email { get; set; }

    public string Instructor_Password { get; set; }

    public virtual Track Track { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}