// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Instructor
{
    public int InstructorId { get; set; }

    public string InstructorFname { get; set; }

    public string InstructorLname { get; set; }

    public string InstructorEmail { get; set; }

    public string InstructorPassword { get; set; }

    public virtual Track Track { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}