// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Question
{
    public int Question_ID { get; set; }

    public string Question_Type { get; set; }

    public string Question_Text { get; set; }

    public string Question_ModelAnswer { get; set; }

    public int? Course_ID { get; set; }

    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    public virtual Course Course { get; set; }

    public virtual ICollection<Student_Exam_Question> Student_Exam_Questions { get; set; } = new List<Student_Exam_Question>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}