// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class SelectStudentsWithTracksResult
    {
        public string Student_FName { get; set; }
        public string Student_LName { get; set; }
        public string Track_Name { get; set; }
    }
}
