// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class SelectBranchesResult
    {
        public int Branch_ID { get; set; }
        public string Branch_Name { get; set; }
    }
}
