// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExSys.Models
{
    public partial class SelectInstructor_CourseResult
    {
        public int Instructor_ID { get; set; }
        public int Course_ID { get; set; }
    }
}
