// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExSys.Models
{
    public partial class SelectTracksResult
    {
        public int Track_ID { get; set; }
        public string Track_Name { get; set; }
        public int Supervisor_ID { get; set; }
    }
}
