// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Data.Models
{
    public partial class ShowStudentCoursesResult
    {
        public string FullName { get; set; }
        public string CourseName { get; set; }
        public int? Student_Grade { get; set; }
    }
}
