// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Student
{
    public int Student_ID { get; set; }

    public string Student_FName { get; set; }

    public string Student_LName { get; set; }

    public string Student_Email { get; set; }

    public string Student_Password { get; set; }

    public int Track_ID { get; set; }

    public virtual ICollection<Student_Course> Student_Courses { get; set; } = new List<Student_Course>();

    public virtual ICollection<Student_Exam_Question> Student_Exam_Questions { get; set; } = new List<Student_Exam_Question>();

    public virtual Track Track { get; set; }
}