// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Student_Exam_Question
{
    public int Student_ID { get; set; }

    public int Exam_ID { get; set; }

    public int Question_ID { get; set; }

    public string Student_QAnswers { get; set; }

    public string Student_QCorrection { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question Question { get; set; }

    public virtual Student Student { get; set; }
}