// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Student_Course
{
    public int Student_ID { get; set; }

    public int Course_ID { get; set; }

    public short? Student_Grade { get; set; }

    public virtual Course Course { get; set; }

    public virtual Student Student { get; set; }
}