// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Topic
{
    public int TopicId { get; set; }

    public string ToName { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}