// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExSys.Models;

public partial class Track
{
    public int TrackId { get; set; }

    public string TrackName { get; set; }

    public int SupervisorId { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual Instructor Supervisor { get; set; }

    public virtual ICollection<Branch> Branches { get; set; } = new List<Branch>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}